### ISSUE TITLE
Do not surround JWT environment variable values in quotes with Docker Compose

### ISSUE THREAD

**Issue by JonnyHaystack** [Fiodin/nextcloudwithooindocker#2]
Hi, thanks for the great guide it has been very helpful.

One snag that I came across was where you say emphatically to surround the values for the JWT_ENABLED and JWT_SECRET environment variables with quotation marks. In Docker Compose, you actually do *not* want to have quotation marks, otherwise you will get an error in Nextcloud when it tries to health check the document server (when you click save after setting the document server URL).

Just thought it might be helpful to include a note about that for people who use Docker Compose.

**Comment by Fiodin** [comment]
Thanks for the hint.
I looked it up and the only thing there was a missing quotation mark after **true**.
I added a notice for the secret that it should not include quotation mark.

Can it be closed?

**Comment by Fiodin** [comment]
I think the main thing at this issue is, that I didn't use Docker Compose. I used the direct Docker Image.
